#!/bin/bash
docker-compose build ui
docker-compose push ui
docker tag maayanlab/cfde-gse:2.0.0 maayanlab/cfde-gse:latest
docker push maayanlab/cfde-gse:latest
# dokku git:from-image cfde-gskg maayanlab/knowledge_graph:1.1.48