#!/bin/bash
docker-compose build kg
docker-compose push kg
docker tag maayanlab/knowledge_graph:1.1.58 maayanlab/knowledge_graph:latest
docker push maayanlab/knowledge_graph:latest
# dokku git:from-image cfde-gskg maayanlab/knowledge_graph:1.1.48